from math import sqrt
ax = int(input(""))
ay = int(input(""))
bx = int(input(""))
by = int(input(""))
a = abs(ax - bx)
b = abs(ay - by)
NUM = (a*a) + (b*b)
c = sqrt(NUM)
print("C se rovná: {0:.4}".format(c))
